export default {
  neighborhoods: [
    { id: '1', name: 'Centro' },
    { id: '2', name: 'Diadema' },
    { id: '3', name: 'Jardim America' },
    { id: '4', name: 'Jardim Palmeiras' },
  ],
  deliveries: [
    {
      id: '1',
      status: 'entregue',
      package_name: 'Pacote 01',
      start_date: '2021-03-16T18:29:50.132Z',
      end_date: '2021-03-16T18:29:50.132Z',
      signature:
        'https://res.cloudinary.com/mykloud/image/upload/v1617913434/fastfeet/signature_uspp5c.png',
      created_at: '2021-04-25T22:40:53.486Z',
      deliveryman: {
        name: 'John Doe',
        avatar_url: null,
      },
      recipient: {
        name: 'Ludwig van Beethoven',
        street: 'Rua Rui Barbosa',
        number: 1729,
        neighborhood: 'Diadema',
        city: 'São Paulo',
        state: 'São Paulo',
        uf: 'SP',
        zip_code: '11985-580',
      },
    },
    {
      id: '2',
      status: 'pendente',
      package_name: 'Pacote 02',
      start_date: null,
      end_date: null,
      signature: null,
      created_at: '2021-03-16T22:40:53.486Z',
      deliveryman: {
        name: 'Gaspar Antunes',
        avatar_url: null,
      },
      recipient: {
        name: 'Wolfgang Amadeus',
        street: 'Rua Salvador',
        number: 1729,
        neighborhood: 'Centro',
        city: 'Rio do Sul',
        state: 'Santa Catarina',
        uf: 'SC',
        zip_code: '00960-580',
      },
    },
    {
      id: '3',
      status: 'retirada',
      package_name: 'Pacote 03',
      start_date: '2021-03-16T18:29:50.132Z',
      end_date: null,
      signature: null,
      created_at: '2021-03-16T22:40:53.486Z',
      deliveryman: {
        name: 'Dai Jiang',
        avatar_url: null,
      },
      recipient: {
        name: 'Johann Sebastian Bach',
        street: 'Av. Tiradentes',
        number: 5650,
        neighborhood: 'Jardim Palmeiras',
        city: 'Ribeirão Preto',
        state: 'São Paulo',
        uf: 'SP',
        zip_code: '15970-580',
      },
    },
    {
      id: '4',
      status: 'cancelada',
      package_name: 'Pacote 04',
      start_date: '2021-03-16T18:29:50.132Z',
      end_date: null,
      signature: null,
      created_at: '2021-03-16T22:40:53.486Z',
      deliveryman: {
        name: 'Tom Hanson',
        avatar_url: null,
      },
      recipient: {
        name: 'Frédéric Chopin',
        street: 'Rua Paraíba',
        number: 1729,
        neighborhood: 'Jardim America',
        city: 'Rio Claro',
        state: 'São Paulo',
        uf: 'SP',
        zip_code: '00960-580',
      },
    },
  ],
  deliverers: [
    {
      id: 1,
      avatar_url: null,
      name: 'John Doe',
      email: 'john@mail.com',
    },
    {
      id: 2,
      avatar_url: null,
      name: 'Gaspar Antunes',
      email: 'gaspar@mail.com',
    },
    {
      id: 3,
      avatar_url: null,
      name: 'Dai Jiang',
      email: 'daijiang@mail.com',
    },
    {
      id: 4,
      avatar_url: null,
      name: 'Tom Hanson',
      email: 'tomhanson@mail.com',
    },
    {
      id: 5,
      avatar_url: null,
      name: 'Marc Franklin',
      email: 'marcfranklin@mail.com',
    },
    {
      id: 6,
      avatar_url: null,
      name: 'Rosetta Castro',
      email: 'rosettacastro@mail.com',
    },
  ],
  issues: [
    {
      id: 1,
      description: 'Destinatário ausente',
    },
    {
      id: 2,
      description: 'Carga roubada',
    },
    {
      id: 3,
      description: 'Infelizmente sofri um acidente que danificou a encomenda',
    },
    {
      id: 4,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec in mauris et felis eleifend elementum vel quis lectus. Vivamus dapibus nisi augue, vitae ultrices ligula elementum at. Proin ut metus in mi tincidunt vestibulum a a felis. Aenean dictum libero eu urna tristique vestibulum. Fusce feugiat justo et augue facilisis, sit amet ornare eros consequat. Suspendisse semper risus feugiat nisl commodo, sed mollis neque auctor. Nullam eu fringilla lectus. Phasellus sed sapien sed turpis imperdiet maximus. Aenean ante nulla, bibendum non facilisis at, facilisis eget ex. In ut quam et tellus aliquet tincidunt.',
    },
  ],
  recipients: [
    {
      id: 1,
      name: 'Ludwig van Beethoven',
      full_address: 'Rua Beethoven, 1729, Diadema - São Paulo',
      street: 'Rua Beethoven',
      number: 1729,
      neighborhood: 'Diadema',
      city: 'São Paulo',
      state: 'São Paulo',
      uf: 'SP',
      zip_code: '00960-580',
    },
    {
      id: 2,
      name: 'Wolfgang Amadeus',
      full_address: 'Rua Beethoven, 1729, Diadema - São Paulo',
      street: 'Rua Beethoven',
      number: 1729,
      neighborhood: 'Diadema',
      city: 'São Paulo',
      state: 'São Paulo',
      uf: 'SP',
      zip_code: '00960-580',
    },
    {
      id: 3,
      name: 'Johann Sebastian Bach',
      full_address: 'Rua Beethoven, 1729, Diadema - São Paulo',
      street: 'Rua Beethoven',
      number: 1729,
      neighborhood: 'Diadema',
      city: 'São Paulo',
      state: 'São Paulo',
      uf: 'SP',
      zip_code: '00960-580',
    },
    {
      id: 4,
      name: 'Frédéric Chopin',
      full_address: 'Rua Beethoven, 1729, Diadema - São Paulo',
      street: 'Rua Beethoven',
      number: 1729,
      neighborhood: 'Diadema',
      city: 'São Paulo',
      state: 'São Paulo',
      uf: 'SP',
      zip_code: '00960-580',
    },
    {
      id: 5,
      name: 'Piotr Ilitch Tchaikovski',
      full_address: 'Rua Beethoven, 1729, Diadema - São Paulo',
      street: 'Rua Beethoven',
      number: 1729,
      neighborhood: 'Diadema',
      city: 'São Paulo',
      state: 'São Paulo',
      uf: 'SP',
      zip_code: '00960-580',
    },
    {
      id: 6,
      name: 'Antonio Vivaldi',
      full_address: 'Rua Beethoven, 1729, Diadema - São Paulo',
      street: 'Rua Beethoven',
      number: 1729,
      neighborhood: 'Diadema',
      city: 'São Paulo',
      state: 'São Paulo',
      uf: 'SP',
      zip_code: '00960-580',
    },
  ],
};
