export default {
  neighborhoods: [
    { id: '1', name: 'Centro' },
    { id: '2', name: 'Diadema' },
    { id: '3', name: 'Jardim America' },
    { id: '4', name: 'Jardim Palmeiras' },
  ],
  deliveries: [
    {
      id: '1',
      status: 'entregue',
      package_name: 'Pacote 01',
      start_date: '2021-03-16T18:29:50.132Z',
      end_date: '2021-03-16T18:29:50.132Z',
      signature:
        'https://res.cloudinary.com/mykloud/image/upload/v1617913434/fastfeet/signature_uspp5c.png',
      created_at: '2021-04-25T22:40:53.486Z',
      deliveryman: {
        name: 'John Doe',
        avatar_url: null,
      },
      recipient: {
        name: 'Ludwig van Beethoven',
        street: 'Rua Rui Barbosa',
        number: 1729,
        neighborhood: 'Diadema',
        city: 'São Paulo',
        state: 'São Paulo',
        uf: 'SP',
        zip_code: '11985-580',
      },
    },
    {
      id: '2',
      status: 'pendente',
      package_name: 'Pacote 02',
      start_date: null,
      end_date: null,
      signature: null,
      created_at: '2021-03-16T22:40:53.486Z',
      deliveryman: {
        name: 'Gaspar Antunes',
        avatar_url: null,
      },
      recipient: {
        name: 'Wolfgang Amadeus',
        street: 'Rua Salvador',
        number: 1729,
        neighborhood: 'Centro',
        city: 'Rio do Sul',
        state: 'Santa Catarina',
        uf: 'SC',
        zip_code: '00960-580',
      },
    },
    {
      id: '3',
      status: 'retirada',
      package_name: 'Pacote 03',
      start_date: '2021-03-16T18:29:50.132Z',
      end_date: null,
      signature: null,
      created_at: '2021-03-16T22:40:53.486Z',
      deliveryman: {
        name: 'Dai Jiang',
        avatar_url: null,
      },
      recipient: {
        name: 'Johann Sebastian Bach',
        street: 'Av. Tiradentes',
        number: 5650,
        neighborhood: 'Jardim Palmeiras',
        city: 'Ribeirão Preto',
        state: 'São Paulo',
        uf: 'SP',
        zip_code: '15970-580',
      },
    },
    {
      id: '4',
      status: 'cancelada',
      package_name: 'Pacote 04',
      start_date: '2021-03-16T18:29:50.132Z',
      end_date: null,
      signature: null,
      created_at: '2021-03-16T22:40:53.486Z',
      deliveryman: {
        name: 'Tom Hanson',
        avatar_url: null,
      },
      recipient: {
        name: 'Frédéric Chopin',
        street: 'Rua Paraíba',
        number: 1729,
        neighborhood: 'Jardim America',
        city: 'Rio Claro',
        state: 'São Paulo',
        uf: 'SP',
        zip_code: '00960-580',
      },
    },
  ],
};
